### ISSUE TITLE
Composer: Kaltura via Packagist

### ISSUE THREAD

**Issue by justinpage** [kaltura/KalturaGeneratedAPIClientsPHP53#1]
## Issue

Under current composer projects, we would love to have the ability to pull in the in Kaltura API client as a vendor package. By doing so, we have the ability to use the module across many projects.
## Solution

There exists a few kaltura pacakges on packagist. However, none are managed by the kaltura team itself. It would be great to pull in a client package like: `kaltura/api-client53` or something along this example.

**Comment by zoharbabin** [comment]
Thanks @KLVTZ !
However, please note that any changes to the client libraries should always be made to the respective client library generator, and not to the generatED client lib repo.
You can find all the client generators under the 'generator' folder at https://github.com/kaltura/server .
You can learn more at: http://knowledge.kaltura.com/node/43
